# Generated by Django 4.1.2 on 2022-10-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='emailVerified',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='requests',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='transactions',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('admin', 'admin'), ('member', 'member'), ('superadmin', 'superadmin')], default='member', max_length=255),
        ),
    ]
