# Generated by Django 4.1.2 on 2022-10-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giaApp', '0002_alter_users_emailverified_alter_users_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profileImage',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
