# Generated by Django 4.1.2 on 2022-10-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giaApp', '0003_alter_users_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='requests',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='transactions',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
