# Generated by Django 4.1.2 on 2022-10-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giaApp', '0004_alter_users_requests_alter_users_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='id',
            new_name='requestId',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='id',
            new_name='transactionId',
        ),
    ]
