# Generated by Django 4.1.2 on 2022-10-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giaApp', '0005_rename_id_request_requestid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='userId',
            new_name='memberId',
        ),
    ]
