# Generated by Django 4.1.2 on 2022-10-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giaApp', '0006_rename_userid_request_memberid'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
