# Generated by Django 4.1.2 on 2022-10-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giaApp', '0007_users_isdeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=255),
        ),
    ]
