# Generated by Django 4.1.2 on 2022-10-31 12:36

from django.db import migrations, models
import django.db.models.deletion
import endpoints.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('memberId', models.CharField(default=endpoints.utils.custom_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(default=None, max_length=255)),
                ('lastname', models.CharField(default=None, max_length=255)),
                ('type', models.CharField(choices=[('admin', 'admin'), ('member', 'member'), ('superadmin', 'superadmin')], default='member', max_length=255)),
                ('dob', models.CharField(default=None, max_length=255)),
                ('gender', models.CharField(default=None, max_length=255)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('pin', models.CharField(default=None, max_length=255)),
                ('phoneNumber', models.CharField(default=None, max_length=255)),
                ('username', models.CharField(default=None, max_length=255)),
                ('memberType', models.CharField(choices=[('student', 'student'), ('nonstudent', 'nonstudent')], default=None, max_length=255)),
                ('profileImage', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('emailVerified', models.BooleanField(default=False, editable=False)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=255)),
                ('transactions', models.TextField(blank=True, default='[]', null=True)),
                ('requests', models.TextField(blank=True, default='[]', null=True)),
                ('transactionsMade', models.CharField(default='0', max_length=255)),
                ('totalInvestment', models.CharField(default='0', max_length=255)),
                ('withdrawalLimit', models.CharField(default='2', max_length=255)),
                ('withdrawalMade', models.CharField(default='0', max_length=255)),
                ('requestsMade', models.CharField(default='0', max_length=255)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'ordering': ['-createdOn'],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transactionId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcationId', models.CharField(default=endpoints.utils.transaction_id, max_length=255, unique=True)),
                ('type', models.CharField(choices=[('withdrawal', 'withdrawal'), ('investment', 'investment')], default=None, max_length=255)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=255)),
                ('amount', models.CharField(default='0.00', max_length=255)),
                ('currency', models.CharField(default='GHS', max_length=255)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_transactions', to='endpoints.users')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updateOn', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=255)),
                ('amount', models.CharField(default='0.00', max_length=255)),
                ('purpose', models.CharField(default=None, max_length=255)),
                ('reason', models.CharField(default=None, max_length=255)),
                ('type', models.CharField(default='business', max_length=255)),
                ('isDeleted', models.BooleanField(default=False)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_request', to='endpoints.users')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghanaCardNumber', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('frontCardPic', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('backCardPic', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='endpoints.users')),
            ],
            options={
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
