# Generated by Django 4.1.2 on 2022-10-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghanaCardNumber', models.CharField(default=None, max_length=255)),
                ('frontCardPic', models.CharField(default=None, max_length=255)),
                ('backCardPic', models.CharField(default=None, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='endpoints.users')),
            ],
        ),
    ]
