# Generated by Django 4.1.2 on 2022-10-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='createdOn',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
