# Generated by Django 4.1.2 on 2022-10-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_alter_request_createdon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
