# Generated by Django 4.1.2 on 2022-11-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_alter_request_createdon'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phoneNumber',
            field=models.TextField(default='[]'),
        ),
    ]
