# Generated by Django 4.1.2 on 2022-10-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_alter_documents_backcardpic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='ghanaCardNumber',
        ),
    ]
