# Generated by Django 4.1.2 on 2022-10-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_remove_users_ghanacardnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='endpoints.users'),
        ),
    ]
