# Generated by Django 4.1.2 on 2022-10-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_alter_documents_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name_plural': 'Documents'},
        ),
    ]
