# Generated by Django 4.1.2 on 2022-11-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_remove_users_address_remove_users_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphonenumber',
            name='userPhoneNumber',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
