# Generated by Django 4.1.2 on 2022-10-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0007_alter_documents_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-createdOn'], 'verbose_name_plural': 'Users'},
        ),
    ]
