# Generated by Django 4.1.2 on 2022-11-03 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0007_alter_userphonenumber_userphonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('phoneNumber', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserPhoneNumber', to='endpoints.users')),
            ],
            options={
                'verbose_name_plural': 'Phone',
            },
        ),
        migrations.RenameModel(
            old_name='UserAddress',
            new_name='Address',
        ),
        migrations.RenameModel(
            old_name='UserEmailAddress',
            new_name='EmailAddress',
        ),
        migrations.RenameField(
            model_name='emailaddress',
            old_name='emailAddress',
            new_name='email',
        ),
        migrations.DeleteModel(
            name='UserPhoneNumber',
        ),
    ]
