# Generated by Django 4.1.2 on 2022-11-03 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0008_phonenumber_rename_useraddress_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAddress', to='endpoints.users'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserPhoneNumber', to='endpoints.users'),
        ),
    ]
