# Generated by Django 4.1.2 on 2022-11-04 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0011_alter_emailaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='endpoints.users'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='type',
            field=models.CharField(blank=True, default='secondary', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='type',
            field=models.CharField(blank=True, default='secondary', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='endpoints.users'),
        ),
    ]
