# Generated by Django 4.1.2 on 2022-11-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0013_alter_address_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='createdOn',
            field=models.CharField(default='04-11-2022 19:52:42', max_length=255),
        ),
    ]
