# Generated by Django 4.1.2 on 2022-11-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0014_activities_alter_users_createdon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['createdOn'], 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='request',
            name='createdOn',
            field=models.CharField(default='04-11-2022 19:55:04', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='createdOn',
            field=models.CharField(default='04-11-2022 19:55:04', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdOn',
            field=models.CharField(default='04-11-2022 19:55:04', max_length=255),
        ),
    ]
