# Generated by Django 4.1.2 on 2022-11-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0015_alter_users_options_alter_request_createdon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='createdOn',
            field=models.CharField(default='05-11-2022 11:22:56', max_length=255),
        ),
        migrations.AddField(
            model_name='activities',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='activities',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='endpoints.users'),
        ),
        migrations.AlterField(
            model_name='request',
            name='createdOn',
            field=models.CharField(default='05-11-2022 11:22:56', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='createdOn',
            field=models.CharField(default='05-11-2022 11:22:56', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdOn',
            field=models.CharField(default='05-11-2022 11:22:56', max_length=255),
        ),
    ]
