# Generated by Django 4.1.2 on 2022-11-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0021_alter_activities_createdon_alter_request_createdon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'ordering': ['createdOn'], 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['createdOn'], 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='activities',
            name='createdOn',
            field=models.CharField(blank=True, default='05-11-2022 13:16:05', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='createdOn',
            field=models.CharField(default='05-11-2022 13:16:05', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='createdOn',
            field=models.CharField(default='05-11-2022 13:16:05', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdOn',
            field=models.CharField(default='05-11-2022 13:16:05', max_length=255),
        ),
    ]
