# Generated by Django 4.1.2 on 2022-11-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0023_alter_activities_options_alter_activities_createdon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='createdOn',
            field=models.CharField(blank=True, default='06-11-2022 14:38:15', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='createdOn',
            field=models.CharField(default='06-11-2022 14:38:15', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='createdOn',
            field=models.CharField(default='06-11-2022 14:38:15', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdOn',
            field=models.CharField(default='06-11-2022 14:38:15', max_length=255),
        ),
    ]
