# Generated by Django 4.1.2 on 2022-11-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0025_alter_activities_createdon_alter_request_createdon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isDeletedOn',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='createdOn',
            field=models.CharField(blank=True, default='10-11-2022 10:18:19', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='createdOn',
            field=models.CharField(default='10-11-2022 10:18:19', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='createdOn',
            field=models.CharField(default='10-11-2022 10:18:19', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdOn',
            field=models.CharField(default='10-11-2022 10:18:19', max_length=255),
        ),
    ]
