# Generated by Django 4.1.2 on 2022-12-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0028_alter_users_isdeletedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='isDeletedOn',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
