# Generated by Django 4.1.2 on 2022-12-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0029_alter_users_isdeletedon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='deleteTotally',
        ),
        migrations.AddField(
            model_name='users',
            name='expireDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
