# Generated by Django 4.1.2 on 2022-12-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0030_remove_users_deletetotally_users_expiredate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-createdOn'], 'verbose_name_plural': 'Users'},
        ),
    ]
